### ISSUE TITLE
Catkin_make error 

### ISSUE THREAD

**Issue by LavrenovRoman** [frontw/voronoi_planner#1]
Hello!
In performing catkin_make it receive an error 
make[2]: *** No rule for make `/home/lavrenovroman/catkin_ws/src/voronoi_planner/cfg/VoronoiPlanner.cfg', for `/home/lavrenovroman/catkin_ws/devel/include/voronoi_planner/VoronoiPlannerConfig.h'. Stop
make[1]: *** [voronoi_planner/CMakeFiles/voronoi_planner_gencfg.dir/all] Error
Thank you in advance!

**Comment by frontw** [comment]
fixed
