### ISSUE TITLE
Infinite loop on findPath function for res3

### ISSUE THREAD

**Issue by sgiraz** [frontw/voronoi_planner#2]
When the code runs on a embedded board like NVIDIA Jetson TX2 or NVIDIA Jetson AGX Xavier, the findPath function for "res3" still increase the size of open nodes up to value ~700 , then it decreases until reach the value zero and return false (value 0).
After this process move base die and the program get in stuck.
Do you think there might be a bug in this implementation of voronoi_planner?

Note: If the code runs on a normal host pc the problem seems disappear.

![photo5841725134463939207](https://user-images.githubusercontent.com/18039045/72681000-12b1de80-3ac0-11ea-969b-0e603c4fc043.jpg)

**Comment by yyomna** [comment]
@sgiraz have you managed to find a solution? I am facing the exact same problem with Jetson Xavier.

**Comment by sgiraz** [comment]
Hi @yyomna, I'm sorry for the late reply, but I was very busy in the last days.
Unfortunately I don't have the solution that you are looking for, cause I didn't work on it anymore.

I remember that I removed (commented) the `findPath` function, and everything was working find on `Jetson` boards. Of course this solution may be not safe and need for more investigation.
